name: NewSite
favicon: null
layout_spectrum: 0.8726605193223804
typography_spectrum: 0.2055469413753599
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.0006237444467842579
  lightness: 0.21027669962495565
  saturation: 0.19285724963992834
  rhythmicContrast: 0.11330987815745175
purpose: []
